# Maintainer: MageEdu <mage@magedu.com>
# Site: https://www.magedu.com
# ElasticSearch Deployment.
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: mall
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
